# Generated by Django 2.1.5 on 2019-10-25 09:02

import QandAs.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_id', models.IntegerField()),
                ('answer_text', models.CharField(max_length=500)),
                ('question_ref', djongo.models.fields.EmbeddedModelField(model_container=QandAs.models.Question, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('question_text', models.CharField(max_length=200)),
                ('question_description', models.CharField(max_length=500)),
            ],
        ),
    ]
