# Generated by Django 2.1.5 on 2019-10-26 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AComment',
            fields=[
                ('ac_id', models.AutoField(primary_key=True, serialize=False)),
                ('ac_text', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('a_text', models.CharField(max_length=500)),
                ('a_isaccepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QComment',
            fields=[
                ('qc_id', models.AutoField(primary_key=True, serialize=False)),
                ('qc_text', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('q_id', models.AutoField(primary_key=True, serialize=False)),
                ('q_text', models.CharField(max_length=250)),
                ('q_desc', models.CharField(max_length=500)),
                ('q_isClosed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UpVote',
            fields=[
                ('up_id', models.IntegerField(primary_key=True, serialize=False)),
                ('a_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.Answer')),
            ],
        ),
        migrations.AddField(
            model_name='qcomment',
            name='q_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='q_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.Question'),
        ),
        migrations.AddField(
            model_name='acomment',
            name='a_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.Answer'),
        ),
    ]
