# Generated by Django 2.1.5 on 2019-10-26 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_auto_20191026_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acomment',
            name='a_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acomments', to='core_app.Answer'),
        ),
    ]
