# Generated by Django 2.1.5 on 2019-10-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_auto_20191026_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvote',
            name='up_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
